spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/family_budget
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  flyway:
    enabled: true

telegram:
  bot:
    name: ${BOT_NAME}
    token: ${BOT_TOKEN}

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE

schedule:
  periodic-rule: "0 * * * * *"
  duty: "0 * * * * *"
  todo-reminder: "0 0 8 * * *"
  submit-meter-reminder: "0 0 * * * *"

datetime:
  day: 23
  hour: 12
  minute: 0